# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='echo_service.proto',
  package='nightfade',
  serialized_pb='\n\x12\x65\x63ho_service.proto\x12\tnightfade\"\x06\n\x04Void\"\x1d\n\nEchoString\x12\x0f\n\x07message\x18\x01 \x02(\t2>\n\x0cIEchoService\x12.\n\x04\x65\x63ho\x12\x15.nightfade.EchoString\x1a\x0f.nightfade.Void2@\n\x0bIEchoClient\x12\x31\n\x07respond\x12\x15.nightfade.EchoString\x1a\x0f.nightfade.VoidB\x06\x80\x01\x01\x90\x01\x01')




_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='nightfade.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=39,
)


_ECHOSTRING = _descriptor.Descriptor(
  name='EchoString',
  full_name='nightfade.EchoString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='nightfade.EchoString.message', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=41,
  serialized_end=70,
)

DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['EchoString'] = _ECHOSTRING

class Void(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VOID

  # @@protoc_insertion_point(class_scope:nightfade.Void)

class EchoString(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ECHOSTRING

  # @@protoc_insertion_point(class_scope:nightfade.EchoString)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\200\001\001\220\001\001')

_IECHOSERVICE = _descriptor.ServiceDescriptor(
  name='IEchoService',
  full_name='nightfade.IEchoService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=72,
  serialized_end=134,
  methods=[
  _descriptor.MethodDescriptor(
    name='echo',
    full_name='nightfade.IEchoService.echo',
    index=0,
    containing_service=None,
    input_type=_ECHOSTRING,
    output_type=_VOID,
    options=None,
  ),
])

class IEchoService(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _IECHOSERVICE
class IEchoService_Stub(IEchoService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _IECHOSERVICE


_IECHOCLIENT = _descriptor.ServiceDescriptor(
  name='IEchoClient',
  full_name='nightfade.IEchoClient',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=136,
  serialized_end=200,
  methods=[
  _descriptor.MethodDescriptor(
    name='respond',
    full_name='nightfade.IEchoClient.respond',
    index=0,
    containing_service=None,
    input_type=_ECHOSTRING,
    output_type=_VOID,
    options=None,
  ),
])

class IEchoClient(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _IECHOCLIENT
class IEchoClient_Stub(IEchoClient):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _IECHOCLIENT

# @@protoc_insertion_point(module_scope)
